version: '3.1'

services:
  server:
    container_name: server
    restart: always
    build:
      context: server
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - webnet
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: 'postgres:14-alpine'
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:
    driver: bridge