version: '3.1'

services:
  server:
    container_name: docker-server
    restart: always
    build:
      context: server
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - webnet
    depends_on:
      - postgres

  postgres:
    container_name: ${POSTGRES_HOST}
    restart: always
    image: 'postgres:14-alpine'
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - webnet

  minio:
    container_name: ${MINIO_HOST}
    restart: unless-stopped
    image: minio/minio
    volumes:
      - ./minio/data:/data
    env_file:
      - .env
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_BROWSER_PORT}:${MINIO_BROWSER_PORT}"
    command: server /data --console-address :${MINIO_BROWSER_PORT}

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:$MINIO_PORT $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb myminio/$MINIO_BUCKET;
      /usr/bin/mc anonymous set public myminio/$MINIO_BUCKET;
      exit 0;
      "

networks:
  webnet:
    driver: bridge
