version: '3.1'

services:
  server:
    container_name: docker-server
    restart: always
    build:
      context: server
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - webnet
    depends_on:
      - postgres

  postgres:
    container_name: ${POSTGRES_HOST}
    image: 'postgres:14-alpine'
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - webnet

networks:
  webnet:
    driver: bridge